export const ADD_TO_HISTORY = 'ADD_TO_HISTORY';
export const UPDATE_HISTORY_QUANTITY = 'UPDATE_HISTORY_QUANTITY';
export const ADD_MULTIPLE_TO_HISTORY = 'ADD_MULTIPLE_TO_HISTORY';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';
export const TOGGLE_HISTORY = 'TOGGLE_HISTORY';